#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

language: java
dist: trusty
jdk:
  - openjdk11

env:
  global:
    JAVA_OPTS=-Xmx4g

cache:
  directories:
    - "$HOME/.m2"
before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/logging/log4j

install:
  - jdk_switcher use openjdk8
  - mvn -t .travis-toolchains.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target /home/travis/openjdk11
  - jdk_switcher use openjdk8
  - mvn -t .travis-toolchains.xml test -B -V

after_success:
  - jdk_switcher use openjdk8
  - mvn -t .travis-toolchains.xml -pl !log4j-bom jacoco:prepare-agent test jacoco:report coveralls:report -B -V
